#!/usr/bin/env node
// Builds a single-file executable with Bun: bun run build.js  (or: node build.js)
//
// Step 1 embeds the page, its icons and the item list into src/embedded-assets.js, so the
// binary needs nothing next to it. Step 2 asks Bun to compile server.js into dist/.
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = __dirname;
const EMBEDDED = path.join(ROOT, 'src', 'embedded-assets.js');
const OUT_DIR = path.join(ROOT, 'dist');
const TARGET = process.argv[2] || 'bun-windows-x64';           // bun-linux-x64, bun-darwin-arm64, ...
const NAME = TARGET.includes('windows') ? 'd2pt.exe' : 'd2pt';

const files = ['ui/index.html', 'data/item_ids.json', ...fs.readdirSync(path.join(ROOT, 'ui', 'assets')).map(f => 'ui/assets/' + f)];

const embedded = {};
for (const rel of files) embedded[rel] = fs.readFileSync(path.join(ROOT, rel)).toString('base64');
fs.writeFileSync(EMBEDDED,
  '// Generated by build.js — the page, icons and item list baked into the packaged build.\n' +
  'module.exports = { files: ' + JSON.stringify(embedded) + ' };\n');
const kb = (fs.statSync(EMBEDDED).size / 1024).toFixed(0);
console.log(`Embedded ${files.length} files (${kb} KB)`);

fs.mkdirSync(OUT_DIR, { recursive: true });
try {
  execFileSync('bun', ['build', 'server.js', '--compile', '--target', TARGET, '--outfile', path.join(OUT_DIR, NAME)],
    { cwd: ROOT, stdio: 'inherit', shell: process.platform === 'win32' });
  const mb = (fs.statSync(path.join(OUT_DIR, NAME)).size / 1024 / 1024).toFixed(1);
  console.log(`\nDone: dist/${NAME} (${mb} MB) — run it, no Node needed.`);
} finally {
  fs.rmSync(EMBEDDED, { force: true }); // running from source should read the real files again
}
