// Where the tool reads its files from and where it keeps its own data.
//
// Run from source (node server.js): everything lives in the project folder.
// Packaged (bun build --compile): the page, icons and the item list are embedded into the
// executable at build time, and the writable data folder sits next to the .exe.
const fs = require('fs');
const path = require('path');

let embedded = null;
try { embedded = require('./embedded-assets'); } catch {} // generated by build.js, only in the packaged build

const PACKAGED = !!embedded;
const ROOT = path.join(__dirname, '..');
const BASE = PACKAGED ? path.dirname(process.execPath) : ROOT;
const DATA = path.join(BASE, 'data');
const OUT = path.join(BASE, 'out');

// `rel` is relative to the project root, e.g. 'ui/index.html' or 'ui/assets/dota.png'.
function readFile(rel) {
  const key = rel.replace(/\\/g, '/');
  if (embedded?.files[key]) return Buffer.from(embedded.files[key], 'base64');
  const f = path.join(ROOT, key);
  return fs.existsSync(f) ? fs.readFileSync(f) : null;
}

// The packaged build starts with an empty data folder; seed it with the embedded item list
// so the first run works even without a connection to OpenDota.
function ensureData() {
  fs.mkdirSync(DATA, { recursive: true });
  const items = path.join(DATA, 'item_ids.json');
  if (PACKAGED && !fs.existsSync(items)) {
    const seed = readFile('data/item_ids.json');
    if (seed) fs.writeFileSync(items, seed);
  }
}

module.exports = { PACKAGED, ROOT, BASE, DATA, OUT, readFile, ensureData };
